"""Экспорт inline-клавиатур приложения."""

from keyboards.admin import (
    admin_broadcast_confirmation_keyboard,
    admin_force_check_confirmation_keyboard,
    admin_logs_keyboard,
    admin_news_keyboard,
    admin_news_moderation_keyboard,
    admin_panel_keyboard,
    admin_restart_confirmation_keyboard,
    admin_stats_keyboard,
    admin_users_keyboard,
    update_confirmation_keyboard,
)
from keyboards.inline import (
    after_departure_date_keyboard,
    currency_keyboard,
    format_search_confirmation,
    language_keyboard,
    location_choice_keyboard,
    nearby_dates_keyboard,
    notification_mode_keyboard,
    news_card_keyboard,
    news_menu_keyboard,
    news_subscriptions_keyboard,
    offer_subscribe_keyboard,
    passengers_keyboard,
    popular_directions_keyboard,
    search_confirmation_keyboard,
    settings_keyboard,
    start_search_keyboard,
    subscriptions_keyboard,
    trip_type_keyboard,
)

__all__ = [
    "admin_broadcast_confirmation_keyboard",
    "admin_force_check_confirmation_keyboard",
    "admin_logs_keyboard",
    "admin_news_keyboard",
    "admin_news_moderation_keyboard",
    "admin_panel_keyboard",
    "admin_restart_confirmation_keyboard",
    "admin_stats_keyboard",
    "admin_users_keyboard",
    "update_confirmation_keyboard",
    "after_departure_date_keyboard",
    "currency_keyboard",
    "format_search_confirmation",
    "language_keyboard",
    "location_choice_keyboard",
    "nearby_dates_keyboard",
    "notification_mode_keyboard",
    "news_card_keyboard",
    "news_menu_keyboard",
    "news_subscriptions_keyboard",
    "offer_subscribe_keyboard",
    "passengers_keyboard",
    "popular_directions_keyboard",
    "search_confirmation_keyboard",
    "settings_keyboard",
    "start_search_keyboard",
    "subscriptions_keyboard",
    "trip_type_keyboard",
]
